### ISSUE TITLE
Incorrect Battery Capacity Detection

### ISSUE THREAD

**Issue by Sahil12524** [redznn/releases#4]
Device: M127G
ROM: crDroidAndroid-12.1-20221207-m12-v8.11.zip

I have a 6000 mAh battery and the ROM detects the battery as 4900 mAh
Please fix it ASAP, thank you.
![Screenshot_20221212-025606_Device Info HW](https://user-images.githubusercontent.com/42999635/206929841-2477c7ea-8ca4-4116-bb12-586ac6a4a5f4.png)

**Comment by redznn** [comment]
Its impossible to fix without a build separated for M127G
