### ISSUE TITLE
Please Mention Description of the changes of New Rom Update

### ISSUE THREAD

**Issue by Sahil12524** [redznn/releases#5]
When ever I come and see there always new rom you release, either update or something else, please mention the description of the what's new, what's fixed etc, because its difficult to know the changes without installing those rom.

Kindly close the issues if they are already fixed!
Thankyou...

**Comment by redznn** [comment]
I put the changes in my telegram builds channel, and in the exynos 850 group, but I'll start putting them here too, thanks
